#!/bin/bash
# validAlphaNum--Ensures that input consists only of alphabetical
# and numeric characters

validAlphaNum()
{
  # Validate arg: return 0 if all upper+lower+digits; 1 otherwise

  # Remove all unacceptable chars.
  validchars="$(echo "$1" | sed -e 's/[^[:alnum:]]//g')"

  if [ "$validchars" = "$1" ] ; then
    return 0
  else
    return 1
  fi
}

# BEGIN MAIN SCRIPT--ONLY EXECUTES IF THE SCRIPT IS RUN AS STANDALONE.
if [ "$BASH_SOURCE" = "$0" ] ; then
  /bin/echo -n "Enter input: "
  read input

  # Input validation
  if ! validAlphaNum "$input" ; then
    echo "Please enter only letters and numbers." >&2
    exit 1
  else
    echo "Input is valid."
  fi
  exit 0
fi

